version: '3.1'

services:

 api-persona:
    build: ./api-persona
    image: marcosechague/apipersona-exam
    restart: always
    container_name: api-persona-exam
    ports:
     - 8080:8080
    environment:
     - host=mysql_server
     - port=3306
    depends_on:
     - mysql_server

 api-preferencia:
    build: ./api-preferencia
    image: marcosechague/apipreferencia-exam
    restart: always
    ports:
     - 8090:8090
    environment:
     - url_apipersona=api-persona
     - host=mysql_server
     - port=3306
    depends_on:
     - mysql_server
     - api-persona

 mysql_server:
    build: ./basedatos
    image: marcosechague/jdevops-bd
    restart: always