version: '3.4'

services:

   jenkins:
    image: marcosechague/jenkins-javadevops
    user: root
    ports:
      - "8181:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins-data:
