version: '3.4'

services:

  tomcat:
    image: tomcat:8.5-jdk8
    environment:
     - host=mysql_server_prod
     - port=3307
    ports:
      - 8282:8080
    restart: on-failure
    container_name: tomcat_javadevops
    networks:
      - netjd

  jenkins:
    image: marcosechague/jenkinsjd
    user: root
    ports:
      - "8181:8080"
      - "8443:8443"
      - "50000:50000"
    networks:
      - netjd
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  mysql_server_prod:
    build: ./basedatos
    image: marcosechague/jdevops-bd
    restart: always
    ports:
      - 3307:3306

volumes:
  jenkins-data:

networks:
  netjd :
    driver : bridge

