version: '3.1'

services:

 api-persona:
    build: ./api-persona
    image: marcosechague/apipersona-exam
    restart: always
    container_name: api-persona-exam
    ports:
     - 8080:8080
    environment:
     - host=mysql_server
     - port=3306
    depends_on:
     - mysql_server

 mysql_server:
    build: ./basedatos
    image: marcosechague/jdevops-bd
    restart: always